data:
  root_dir: ../data
  train_csv: ../data/processed_chexpert_age_gender_split/train.csv
  val_csv: ../data/processed_chexpert_age_gender_split/val.csv
  test_csv: ../data/processed_chexpert_age_gender_split/test.csv
  batch_size: 64
  num_workers: 16
  pin_memory: true
  prefetch_factor: 2
  persistent_workers: true
  image_size: 224
  resize: 256
training:
  epochs: 10
  lr_head: 3e-4
  lr_full: 1e-5
  weight_decay: 1e-4
freeze_schedule:
  warmup_epochs: 3
labels:
- No Finding
- Enlarged Cardiomediastinum
- Cardiomegaly
- Lung Opacity
- Lung Lesion
- Edema
- Consolidation
- Pneumonia
- Atelectasis
- Pneumothorax
- Pleural Effusion
- Pleural Other
- Fracture
- Support Devices
model:
  name: efficientnet_b4
  pretrained: true
  hf_name: google/efficientnet-b4
num_classes: 14
