data:
  root_dir: ../datasets
  train_csv: ../datasets/processed_chexpert_age_gender_split/train.csv
  val_csv: ../datasets/processed_chexpert_age_gender_split/val.csv
  test_csv: ../datasets/processed_chexpert_age_gender_split/test.csv
  batch_size: 32
  num_workers: 4
  pin_memory: true
  image_size: 224
  resize: 256

training:
  epochs: 10
  lr_head: 3e-4
  lr_full: 1e-5
  weight_decay: 1e-4

freeze_schedule:
  warmup_epochs: 3

labels:
  - No Finding
  - Enlarged Cardiomediastinum
  - Cardiomegaly
  - Lung Opacity
  - Lung Lesion
  - Edema
  - Consolidation
  - Pneumonia
  - Atelectasis
  - Pneumothorax
  - Pleural Effusion
  - Pleural Other
  - Fracture
  - Support Devices
